### ISSUE TITLE
לבנות ממסד נתונים

### ISSUE THREAD

**Issue by mysticpea** [mysticpea/DFG_Stability_Bicycle#5]

**Comment by roee-zehavi** [comment]
![drawSQL-image-export-2024-09-30](https://github.com/user-attachments/assets/3d2f00b5-86fe-4c74-bdbc-bcbb770e96c0)
טיוטה ראשונה לסכמת נתונים

**Comment by roee-zehavi** [comment]
קישור לאתר שאני עובד איתו

https://drawsql.app/diagrams

**Comment by roee-zehavi** [comment]
הכנסתי חלק מהממסד נתונים,
מצרף תמונה
![image](https://github.com/user-attachments/assets/cba579ce-99a2-4f78-baf1-ea53aeccc0de)

צריך להוסיף את שימרת הנתונים מהניסוי
